id: ICB70FBF8
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:15:38.841295
last_modified: 2023-02-08 15:15:38.841378
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: en
bases:
  2AFB:
    base_file: 2AFB.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
